AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Resources:
  MahjongCsvToMongoDBFunction:
    Type: "AWS::Serverless::Function"
    Properties:
      Handler: build/index.handler
      Runtime: nodejs18.x
      CodeUri: .
      MemorySize: 1024
      Timeout: 120
      Environment:
        Variables:
          GOOGLE_SERVICE_ACCOUNT_EMAIL: GOOGLE_SERVICE_ACCOUNT_EMAIL
          GOOGLE_PRIVATE_KEY: GOOGLE_PRIVATE_KEY
          GOOGLE_SHEET_ID: GOOGLE_SHEET_ID
          MONGO_URI: MONGO_URI
          TZ: 'Asia/Tokyo'
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: ["src/index.ts"]
    Events:
      SQSTrigger:
        Type: SQS
        Properties:
          Queue: !GetAtt MahjongScoreQueue.Arn

  MahjongScoreQueue:
    Type: 'AWS::SQS::Queue'
    Properties:
      QueueName: "MahjongScoreQueue"
      VisibilityTimeout: 30
