AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Parameters:
  MongoDBUri:
    Type: String
    Description: "MongoDB URI"
  GoogleServiceAccountEmail:
    Type: String
    Description: "Google Service Account Email"
  GooglePrivateKey:
    Type: String
    Description: "Google Private Key"
  GoogleSheetId:
    Type: String
    Description: "Google Sheet ID"

Resources:
  MahjongScoreLambdaFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: build/index.handler
      Runtime: nodejs18.x
      CodeUri: .
      MemorySize: 128
      Timeout: 60
      Environment:
        Variables:
          NODE_ENV: production
          MONGO_URI: !Ref MongoDBUri
          GOOGLE_SERVICE_ACCOUNT_EMAIL: !Ref GoogleServiceAccountEmail
          GOOGLE_PRIVATE_KEY: !Ref GooglePrivateKey
          GOOGLE_SHEET_ID: !Ref GoogleSheetId
      Events:
        SQSTrigger:
          Type: SQS
          Properties:
            Queue: !GetAtt MahjongQueue.Arn

  MahjongQueue:
    Type: 'AWS::SQS::Queue'
    Properties:
      QueueName: "MahjongQueue"
      VisibilityTimeout: 90

Outputs:
  LambdaFunction:
    Description: "Mahjong Score Lambda Function ARN"
    Value: !GetAtt MahjongScoreLambdaFunction.Arn
  QueueURL:
    Description: "URL of the SQS Queue"
    Value: !Ref MahjongQueue
